package io.github.rrbca2022.pms.services;

import io.github.rrbca2022.pms.entity.Category;
import io.github.rrbca2022.pms.entity.Medicine;
import io.github.rrbca2022.pms.entity.MedicineBatch;
import io.github.rrbca2022.pms.repository.MedicineBatchRepository;
import io.github.rrbca2022.pms.repository.MedicineRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class MedicineService {

    private final CategoryService categoryService;
    private final MedicineRepository medicineRepository;
    private final MedicineBatchRepository batchRepository; // New Repository

    public MedicineService(MedicineRepository medicineRepository,
                           CategoryService categoryService,
                           MedicineBatchRepository batchRepository) {
        this.medicineRepository = medicineRepository;
        this.categoryService = categoryService;
        this.batchRepository = batchRepository;
    }

    public List<Medicine> getAllMedicines(){return medicineRepository.findAll();}

    public Medicine getMedicineById(Long id){return medicineRepository.findById(id).orElse(null);}

    public void saveMedicine(Medicine medicine)
    {
        Long catId=medicine.getCategory().getId();
        Category category=categoryService.getCategoryById(catId);
        medicine.setCategory(category);
        Medicine savedMedicine=medicineRepository.save(medicine);

        // 3. Create the Initial Batch from the Medicine form data
        // This makes sure your FEFO algorithm has a record to track.
        MedicineBatch initialBatch = new MedicineBatch();
        initialBatch.setMedicine(savedMedicine);
        initialBatch.setExpiryDate(medicine.getExpDate());
        initialBatch.setStockQuantity(medicine.getQty());

        // Note: 'batchNumber' will be auto-generated by @PrePersist in the entity
        // if you don't set it here.

        batchRepository.save(initialBatch);
    }

    public void deleteMedicine(Long id){ medicineRepository.deleteById(id);}




}
